name: Java CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Download allurectl
      run: |
        wget https://github.com/allure-framework/allurectl/releases/latest/download/allurectl_linux_386 -O /usr/bin/allurectl \
        chmod +x /usr/bin/allurectl
    - name: Build with Gradle
      run: ./gradlew test
    - name: Upload allure results
      run: ./allurectl upload build/allure-results
      continue-on-error: true
      env:
        ALLURE_ENDPOINT: ${{ secrets.ALLURE_ENDPOINT }}
        ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
        ALLURE_PROJECT_ID: ${{ secrets.ALLURE_PROJECT_ID }}
